# Generated by Django 6.0.1 on 2026-01-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ['nome'], 'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fornecedor',
            field=models.CharField(max_length=100, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='lote',
            field=models.CharField(max_length=50, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade em estoque'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='validade',
            field=models.DateField(verbose_name='Data de validade'),
        ),
    ]
