# Generated by Django 6.0.1 on 2026-02-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_alter_medicamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='categoria',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='estoque_min',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque mínimo'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='miligrama',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Dosagem (mg/ml)'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='valor_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor unitário'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome do medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade em estoque'),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['nome'], name='idx_medic_nome'),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['categoria'], name='idx_medic_categoria'),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['validade'], name='idx_medic_validade'),
        ),
        migrations.AddConstraint(
            model_name='medicamento',
            constraint=models.UniqueConstraint(condition=models.Q(('miligrama__isnull', False)), fields=('nome', 'lote', 'miligrama'), name='uq_medic_nome_lote_mg'),
        ),
        migrations.AddConstraint(
            model_name='medicamento',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 0), ('estoque_min__gte', 0), ('valor_unit__gte', 0)), name='ck_medic_valores_nao_negativos'),
        ),
    ]
