# Generated by Django 6.0.1 on 2026-02-23 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='fornecedor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos', to='farmacia.fornecedor', verbose_name='Fornecedor (relacionado)'),
        ),
    ]
