# Generated by Django 6.0.1 on 2026-02-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_migrar_fornecedor_para_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='fornecedor_fk',
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos', to='farmacia.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
