# Generated by Django 6.0.1 on 2026-02-23 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_remove_medicamento_fornecedor_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='farmacia.medicamento', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_movimentacao'],
                'indexes': [models.Index(fields=['tipo'], name='idx_mov_tipo'), models.Index(fields=['data_movimentacao'], name='idx_mov_data')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='ck_mov_qtd_maior_que_zero')],
            },
        ),
    ]
