# Generated by Django 6.0.1 on 2026-04-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0009_fornecedor_ativo_fornecedor_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
