# Generated by Django 6.0.1 on 2026-04-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0010_medicamento_descricao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicamento',
            name='ck_medic_valores_nao_negativos',
        ),
        migrations.AddConstraint(
            model_name='medicamento',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 0), ('valor_unit__gte', 0)), name='ck_medic_valores_nao_negativos'),
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='estoque_min',
        ),
    ]
