# Generated by Django 6.0.1 on 2026-04-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0011_remove_medicamento_ck_medic_valores_nao_negativos_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicamento',
            name='uq_medic_nome_lote_mg',
        ),
        migrations.AddConstraint(
            model_name='medicamento',
            constraint=models.UniqueConstraint(fields=('nome', 'miligrama', 'categoria', 'lote', 'validade', 'valor_unit', 'fornecedor'), name='uq_medic_entrada_unica'),
        ),
    ]
